[package]
name = "gif_encoder_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
gif_encoder = { path = "../gif_encoder" }
anyhow = { workspace = true }
criterion = "0.4"
base64 = "0.22.1"
clipboard = "0.5.0"

[dev-dependencies]
criterion = "0.4"
